version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback-server
    command: ["node", "server.js"]
    ports:
      - "4000:4000"
    depende_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    container_name: feedback-worker
    command: ["node", "worker.js"]
    depends_on:
      - redis
    env_file:
      - .env
